### ISSUE TITLE
Accessing Kafka record key in transformations/sinks

### ISSUE THREAD

**Issue by hekonsek** [cescoffier/fluid#2]
Hi,

Is there a way to access Kafka record key in Fluid transformations and sinks? For example in the following snippet, I can access only values of the records, not keys of the latter.

```
KafkaSource<Integer> source = new KafkaSource<>(vertx,
            getKafkaConfig()
                .put("topic", topic)
                .put("value.serializer", IntegerSerializer.class.getName())
                .put("value.deserializer", IntegerDeserializer.class.getName())
        );
        
        List<Integer> results = new ArrayList<>();
        source
            .transform(i -> i + 1)
            .to(Sink.forEach(results::add));
```

This is fine for this simple example, but in real world Kafka usage scenarios, key carries usually an important information. For example this is common to use Kafka in event-sourcing-like scenarios where key indicates ID of the entity and value its latest state. For example if you would like to create materialized view of the stream, I'd like to create something similar to:

    source.to(Sink.forEach(key, value -> mydb.saveOrUpdate(key, value)));

Have you already thought about such use case? That would be extra important for many users.

**Comment by hekonsek** [comment]
The thing here is that the notion of event with key/ID is something that is not applicable for all messaging middleware systems. It makes sense for some, like Kafka. So one solution for this, could be to provide a kind of generic Fluid wrapper class that can be used for messaging systems supporting events with IDs. Something like:

    static class EventWithId<K,V> {   
        K key;   
        V value;   
    }

Then you could create source wrapping event with ID if needed: 

    KafkaSource<EventWithId<String, Bytes>> source = new KafkaSource<>(vertx,
            getKafkaConfig()
                .put("topic", topic).put("includeId", true);
        );

    source
        .to(Sink.forEach(event -> System.out.println("key: " + event.key + " value: " + event.value)));

**Comment by hekonsek** [comment]
BTW I guess that you might have similar issue with messaging middleware system supporting message with headers. For example for AMQP. So as AMQP user I sometimes would like to consume not only body, but also headers of message if needed.

If you can support message headers, then we could use that for carrying record key, as well, by mapping Kafka key to a message header: 

```
static class Event<T> {   
    Map<String, Object> headers;   
    T payload;   
}
```

And then...

```
KafkaSource<Event<String, Bytes>> source = new KafkaSource<>(vertx,
        getKafkaConfig()
            .put("topic", topic).put("wrapEvent", true);
    );

source
    .to(Sink.forEach(event -> System.out.println("key: " + event.headers.get("kafka_key") + " value: " + event.value)));
```

**Comment by cescoffier** [comment]
We were thinking about adding this abstraction. But naming is hard here. `header` and `payload` is pretty close to HTTP, which is good and bad at the same time. 

I had in mind: `Data<T> { T content,  Map<String, Object> baggage}`, and so let Source and Sink to generate this structure as they want.

**Comment by hekonsek** [comment]
In this event wrapper approach here [1] is where it has to be checked if value should be wrapped into "fat event" together with metadata like record key. I think that would make sense - to give end user a choice between working with flat message value object (like now) and "fat events" including headers metadata.

Just saying ;) .

[1] https://github.com/cescoffier/fluid/blob/work/kafka-connector/src/main/java/me/escoffier/fluid/kafka/KafkaSource.java#L23

**Comment by cescoffier** [comment]
Exactly!

**Comment by hekonsek** [comment]
Great to hear that we're at the same page here!

When it comes to naming, I think I personally like payload+headers (like in Spring Integration) or body+headers (like in Camel) conventions. But content+baggage sounds fair to me as well.

You mentioned that you wanna let source and sink to generate / read this structure as they want. I guess that in practice that would mean that almost all sources gonna generate `Data` events (aka "fat events") instead of raw values (aka "thin events"). Kafka needs that key and record metadata (like topic, partition, offset, etc). JMS for messages headers. AMQP for message properties. Even Vert.x event bus connector messages have headers. I'm personally OK with that, as I think that in majority of the real applications people will fallback to "fat events" anyway - I'm just wondering if it makes sense to support "thin events" at all if it is difficult to find a source that doesn't require headers support :) .

**Comment by cescoffier** [comment]
In fact (and why I called them baggage) I believe the transformation stage may be able to write data into this set of "headers", that may influence how the dispatching (sink) is done. 

In addition, we have input and output headers. Are they copied as there arrive? What about header having a transport semantic that we should / must not forward (security header for instance).

Maybe:

```
class Data<T> {
    T payload;
    Map<String, String> headers //  received, immutable
    Map<String, Object> baggage // mutable, headers for the output message are taken from this map
}
```

But we quickly see that it becomes a bit more complex.

**Comment by hekonsek** [comment]
I like the idea of being able to affect a sink dispatching process by writing headers/baggage. This is something I wanted to discuss as well, as I know already that we're gonna need such feature.

This idea of having headers for input and baggage for output headers is cool. That would mean that by default input headers are not copied into output message. I like it :) .

**Comment by ppatierno** [comment]
Just some thoughts about this ...

Remember that Kafka (starting from latest versions) has "headers" as well and the key message is not part of them. Will the baggage part contain both ?

Regarding AMQP 1.0 the scenario is more complex because we have : header, delivery annotations, message annotations, system properties, application properties. The header and the system properties are well defined by the spec while the others are up to the user and they are useful for different cases. Using a "generic" fat events will all these fields be inside the same baggage ?

Finally, thinking about using fluid with MQTT as well (which fits really well thanks to its pub/sub nature), thin events make still sense because there are no headers (at least in the current 3.1.1 version; they'll be supported in v5).

**Comment by hekonsek** [comment]
Wow! Kafka supports headers starting from 0.11 indeed! How could I miss that? :)

I would say that we should squeeze everything into headers/baggage as we need a single abstraction for all transports anyway. We can use headers key prefixes for that purpose like `kafka.key`, 'kafka.header.foo', etc. The same applies for AQMP - `amqp.subject`, `amqp.properties.foo`, etc.

What do you think?

**Comment by hekonsek** [comment]
@cescoffier I think we mentioned that RxJava provides something similar to thread local. Was that custom scheduler [1] by any chance?

[1] https://groups.google.com/forum/#!topic/rxjava/9L04__vPCB8

**Comment by cescoffier** [comment]
Nope, it’s called plugin or hook: https://github.com/ReactiveX/RxJava/wiki/Plugins

**Comment by hekonsek** [comment]
I'm wondering if we can proceed with this one. I guess that #7 is more like an addition to new `Data` structure - a way to access data without passing it explicitly to functions. However I guess that even now we can settle an agreement on `Data` structure and add it to project.

What do you think?

**Comment by cescoffier** [comment]
Sorry to not have commented before on this. We had a talk with @mbogoevici  and we are actually moving toward a bit different direction. We are going to come with our own "unified event" model. So basically:

`Source<Data<T>>` instead of `Source<T>`

@mbogoevici thinks it's possible to detect from the method signature is it consumed a stream of `<T>` or a stream of `<Data<T>>`.

**Comment by hekonsek** [comment]
Can you demonstrate how this new API will look like?

**Comment by cescoffier** [comment]
That's the beauty of the idea, it does not really change the API. If you are interested in the content/payload only:

```java
from("my-source")
   .transform(s -> s.toUppaderCase())
   .to("my-output");
```

If you want the _fat_ object:

```
from("my-source")
    .transform(data -> {
        String h = data.header("X-My-Header);
        String payload = data.payload();
        ....
        // Not yet determined if you need to return a `data` or just the `payload`. 
    })
    .to("my-output");
```

**Comment by hekonsek** [comment]
Cool, so I assume that we just need to:
- create `Data(headers, payload)` class
- create overrloaded versions of `DataStream` methods like `DataStream.transport(Data -> Data)` and `DataStream.transport(Data -> payload)` (BTW I think we should support both "fat" and "thin" return types)
- modify `Source` implementation to generate `Data` events instead of raw values

Am I missing something? Also have you guys got an agreement regarding the final shape of `Data` structure?

**Comment by cescoffier** [comment]
@hekonsek Work in progress... Will push a new branch later today.

**Comment by hekonsek** [comment]
Cool, great to hear that!

**Comment by hekonsek** [comment]
I'm closing this issue now, as #21 has been merged. Many thanks, @cescoffier.
