### ISSUE TITLE
Start releasing project

### ISSUE THREAD

**Issue by hekonsek** [cescoffier/fluid#31]
Hi @cescoffier,

Maybe we can consider releasing very early versions of Fluid to Maven Central? Something like 0.x versions. That would help early adopters (like myself) to create POCs and demos related to the project.

We we also make sure that "release button" is properly set up :) .

**Comment by cescoffier** [comment]
I agree! I would like to have windowing and error management done before releasing the first version. Hopefully, this will be completed this week. 

windowing is quite straightforward to implement, but error management is another story... Right now if any stage throws an error, we don't cut the continuous flow.

**Comment by hekonsek** [comment]
Great. I'm trying to figure out options we have for error handling as well.

When it comes to release process in general it would be awesome to have as many releases as possible at this stage of the project. That would make an adoption of the project easier :) .

**Comment by cescoffier** [comment]
@hekonsek just some news.... finally making progress on windowing and error handling: https://github.com/cescoffier/fluid/issues/32

**Comment by cescoffier** [comment]
0.8 has been released!
