### ISSUE TITLE
Configure a CI

### ISSUE THREAD

**Issue by cescoffier** [cescoffier/fluid#4]

**Comment by hekonsek** [comment]
I've just added Travis CI config file. Can you enable project build on Travis site? Until you have something against Travis of course :) .

**Comment by hekonsek** [comment]
I have also added Travis build status indicator to the main page of the project. It will start displaying current build status as soon as you enable building on Travis site.

**Comment by cescoffier** [comment]
I love Travis reports 👍

**Comment by cescoffier** [comment]
Widget added. BTW back on `master`

**Comment by cescoffier** [comment]
Ok, so we have a CI (travis) publishing snapshot to Sonatype OSS Snapshot. 

Notifications are sent to me, @hekonsek what would you prefer: a dedicated mailing list or each contributor can write his name in the travis file.

**Comment by hekonsek** [comment]
+1 for moving back to master :) .

I think that individual list is better. One thing (mailing list) less to maintain. Added myself (https://github.com/cescoffier/fluid/commit/b77c441fd0ca97b6405f30f00fd06d572c93cc25) to Travis notifications list.

**Comment by hekonsek** [comment]
I guess we can close this one now.

**Comment by cescoffier** [comment]
Yes, was just waiting for your feedback! Thanks again for having initiated this task.
