### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by cescoffier** [cescoffier/fluid#5]
Content should mention:

* project objectives in the README
* build instruction
* how to start using fluid

**Comment by hekonsek** [comment]
I have added almost empty [1] readme file as a part of #4 to display Travis CI status there.

[1] https://github.com/cescoffier/fluid/commit/5b495ab66909f72dc1a41f329068e51a406b936d

**Comment by hekonsek** [comment]
I love this "Fluid - feed your data lake" . Big +1 for this project header :) .

**Comment by cescoffier** [comment]
Work done.
